Solve arrays chellenge
kanigreg/ru-study-ruby pull request #1
Opened 2022-06-08 15:49 UTC by kanigreg

2022-08-01 19:19 UTC, NickelGit requested changes

2022-08-01 19:19 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        iter = array.each
Давай лучше используем `array.each` в качестве самого итератора, без вынесения его в отдельную переменную. Т.к. итератор в отдельной переменной не дает нам каких то особых профитов.
```
array.each do |item|
  ...some code...
end
```

2022-08-01 19:19 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        max = iter.next
подход с использованием первого элемента массива как изначальный максимум верная! Но давай переделаем это присвоение исходя из использования `array.each` без вынесения итератора в переменную.

2022-08-01 19:19 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search_helper = lambda do |left, right|
Действительно ли нам тут нужна лямбда? Если она использована тут только для добавления аргументов left & right, то для упрощения кода лучше просто добавить аргументы со значениями по умолчанию. 
https://medium.com/@sologoubalex/parameters-with-default-values-in-ruby-74cd0e830681

2022-08-01 19:19 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +          return -1 if left > right
единственное ли это условие выхода из рекурсии? как насчет случаев когда число которое мы ищем меньше самого маленького числа в массиве, или больше самого большого?

2022-08-01 19:19 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        search_helper.call(0, array.length - 1)
Давай для улучшения читаемости кода попробуем разбить эти условия на несколько шагов.
1) Проверка что средний элемент это элемент который мы ищем. `return value if condition`
2) тернарная операция определяющая в какой части массива нам необходимо искать дальше. https://www.rubyguides.com/2019/10/ruby-ternary-operator/

2022-08-08 08:58 UTC, kanigreg commented on test/exercise/arrays/solution.rb
> +          return -1 if left > right
Я думаю, что при этих случаях будет ответом `-1` указывающий, что такого элемента в этом массиве нет.

2025-05-12 11:31 UTC, closed without merging